### ISSUE TITLE
No way of clearing items, setItems will append to existing items...

### ISSUE THREAD

**Issue by js-bonin** [itsnothingg/RecursiveRecyclerView#1]
Hey, it seems there si no way of replacing the current item list with another as we can't clear items and `setItems` always add to the current list instead of replacing.

I guess I could simply instantiate another adapter but it's a bit ugly...

Could we just expose a `clearItems()` method that would clear `mItems`

` public void clearItems() {
        if (mItems != null) {
            mItems.clear();
        }
    }`

#2

**Comment by itsnothingg** [comment]
thanks
